#前缀路径
#server:
#  servlet:
#    context-path: /tvmanage # 访问地址：http://localhost:8090/tvmanage/
#测试环境
#spring:
#  profiles:
#    active: dev
#生产环境
spring:
  profiles:
    active: prod
# 文件上传大小设置 单个文件大小/总上传的数据大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 10000MB
#activiti工作流
  activiti:   
#校验流程文件，默认校验resources下的processes文件夹里的流程文件  
    check-process-definitions: true 
    database-schema-update: true
    process-definition-location-prefix: classpath:/processes/
    history-level: full 
    
#mybatis 配置  
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.skyworth.entity
  configuration:
    call-setters-on-nulls: true
    return-instance-for-empty-row: true
#日志配置
logging:
  config: classpath:logback-spring.xml
#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
