#自定义静态资源目录
web:
  upload-path: F:/files/tvmanage
#前缀路径
server:
  servlet:
    context-path: /tvmanage # 访问地址：http://localhost:8090/tvmanage/
#测试环境
spring:
  profiles:
    active: dev
#开发环境
#spring:
#  profiles:
#    active: prod
# 文件上传大小设置 单个文件大小/总上传的数据大小
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB
#数据库连接
  datasource:
# JDBC 配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skyworth_db?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: 123456   
# druid 连接池配置 begin
    type: com.alibaba.druid.pool.DruidDataSource  
    druid:
      initial-size: 5   #初始化连接大小
      min-idle: 5       #最小连接池数量
      max-active: 20    #最大连接池数量
      max-wait: 60000   #获取连接时最大等待时间，单位毫秒
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000   #配置一个连接在池中最小生存的时间，单位是毫秒     
      validation-query: select 'x'             #测试连接
      test-while-idle: true                    #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-on-borrow: false                    #获取连接时执行检测，建议关闭，影响性能
      test-on-return: false                    #归还连接时执行检测，建议关闭，影响性能
      pool-prepared-statements: false          #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭           
      filters: stat,wall,slf4j                 #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 #打开mergeSql功能；慢SQL记录
      useGlobalDataSourceStat: true            #合并多个DruidDataSource的监控数据 
#映射静态资源 
  resources:
    static-locations: classpath:/resources/,classpath:/static/,file:${web.upload-path}
#redis配置
  redis:
    host: localhost   # Redis服务器地址   
    port: 6379        # Redis服务器连接端口 
    max-idle: 8       # 连接池中的最大空闲连接   
    min-idle: 0       # 连接池中的最小空闲连接   
    max-active: 8     # 连接池最大连接数（使用负值表示没有限制） 
    max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制） 
    timeout: 0        # 连接超时时间（毫秒）  
#mybatis 配置  
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.skyworth.entity
  configuration:
     call-setters-on-nulls: true
#日志配置
logging:
  config: src\main\resources\logback-spring.xml
#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
